### ISSUE TITLE
crash after killin first mob with soul shard

### ISSUE THREAD

**Issue by seulil** [CreeperHost/SoulShards#6] opened 2022-06-12 19:13 UTC
Error: java.lang.NullPointerException: Cannot invoke "java.util.Map$Entry.getValue()" because the return value of "java.util.TreeMap.floorEntry(Object)" is null when kill "first mob" holding a soul shard

--- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/12/22, 9:08 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.Map$Entry.getValue()" because the return value of "java.util.TreeMap.floorEntry(Object)" is null
	at net.creeperhost.soulshardsrespawn.core.data.Binding.getTier(Binding.java:86) ~[soulshards-1.18.2-1.2.2.jar%23180!/:1.18.2-1.2.2] {re:classloading}
	at net.creeperhost.soulshardsrespawn.SoulShards.lambda$setupClient$1(SoulShards.java:66) ~[soulshards-1.18.2-1.2.2.jar%23180!/:1.18.2-1.2.2] {re:classloading}
	at net.minecraft.client.renderer.block.model.ItemOverrides.m_173464_(ItemOverrides.java:83) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174264_(ItemRenderer.java:219) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinItemRenderer,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174242_(ItemRenderer.java:229) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinItemRenderer,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109322_(ItemInHandRenderer.java:123) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:client.MixinItemInHandRenderer,pl:mixin:APP:elementalcraft.mixins.json:MixinItemInHandRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java:466) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:client.MixinItemInHandRenderer,pl:mixin:APP:elementalcraft.mixins.json:MixinItemInHandRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:290) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:client.MixinItemInHandRenderer,pl:mixin:APP:elementalcraft.mixins.json:MixinItemInHandRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:778) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1067) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.41.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.creeperhost.soulshardsrespawn.core.data.Binding.getTier(Binding.java:86) ~[soulshards-1.18.2-1.2.2.jar%23180!/:1.18.2-1.2.2] {re:classloading}
	at net.creeperhost.soulshardsrespawn.SoulShards.lambda$setupClient$1(SoulShards.java:66) ~[soulshards-1.18.2-1.2.2.jar%23180!/:1.18.2-1.2.2] {re:classloading}
	at net.minecraft.client.renderer.block.model.ItemOverrides.m_173464_(ItemOverrides.java:83) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174264_(ItemRenderer.java:219) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinItemRenderer,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174242_(ItemRenderer.java:229) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinItemRenderer,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109322_(ItemInHandRenderer.java:123) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:client.MixinItemInHandRenderer,pl:mixin:APP:elementalcraft.mixins.json:MixinItemInHandRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java:466) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:client.MixinItemInHandRenderer,pl:mixin:APP:elementalcraft.mixins.json:MixinItemInHandRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:290) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:client.MixinItemInHandRenderer,pl:mixin:APP:elementalcraft.mixins.json:MixinItemInHandRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:778) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1067) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Seulil'/52, l='ClientLevel', x=622.43, y=72.98, z=247.14]]
	Chunk stats: 961, 609
	Level dimension: minecraft:the_nether
	Level spawn location: World: (-272,64,-160), Section: (at 0,0,0 in -17,4,-10; chunk contains blocks -272,0,-160 to -257,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 987805 game time, 1247953 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2260) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23210!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.41.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by gigabit101** [comment] 2022-06-14 09:43
What mob did you kill?

**Comment by seulil** [comment] 2022-06-14 10:35
Blaze in nether fortress with attempt to consume nearby spawner too

**Comment by gigabit101** [comment] 2022-06-14 13:00
I cant get this to happen, What Modpack are you playing?

**Comment by seulil** [comment] 2022-06-14 13:46
Almost DW20 1.8 pack...without few mods...and added 3 my own...one is adding mobs btw.. maybe heres problem.
Full list can add later. At work atm.

**Comment by gigabit101** [comment] 2022-06-14 14:52
Are you using a texture pack by any chance?

**Comment by seulil** [comment] 2022-06-14 15:22
Nope. But also when logging back got two second play before another ceash...and I saw hotbar was emty and crashes again trying to acces inventory. Only disabling Your mod givving me acces to this save. Also reversing to backup and trying that again with the same resultat.

**Comment by gigabit101** [comment] 2022-06-14 16:11
Just tried this in the latest version Direwolf 1.18 and it works fine, Do you have a list of mods you have added?

**Comment by seulil** [comment] 2022-06-14 17:25
added:
Better animals plus(this one add alotof mobs)
Budshies morph mod
Ender storage(codeChicken's) instead of ender tanks and ender chests
Hexerei
Level Hearts

**Comment by gigabit101** [comment] 2022-07-06 15:47
Still not able to reproduce the issue, Gonna close this issue as I have no way to recreate the issue and no one else is having the issue

**Closed as completed by gigabit101** 2022-07-06 15:47 UTC
